version: '3.9'
services:
  parser_service:
    build: ./parser_service
    container_name: parser_service
    image: parser_service:latest
    ports:
      - '50051:50051'

  analyzer_service:
    build: ./analyzer_service
    container_name: analyzer_service
    image: analyzer_service:latest
    ports:
      - '50052:50052'

  gateway:
    build: ./gateway
    container_name: gateway
    image: gateway:latest
    depends_on:
      - parser_service
      - analyzer_service
    ports:
      - '8080:8080'
    environment:
      PARSER_SERVICE_HOST: 'parser_service'
      ANALYZER_SERVICE_HOST: 'analyzer_service'
