# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analyzer.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'analyzer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61nalyzer.proto\x12\x08\x61nalyzer\"9\n\x0e\x41nalyzeRequest\x12\x16\n\x0e\x63orrelation_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\xa3\x03\n\x0f\x41nalyzeResponse\x12\x16\n\x0e\x63orrelation_id\x18\x01 \x01(\t\x12T\n\x16\x66requency_distribution\x18\x02 \x03(\x0b\x32\x34.analyzer.AnalyzeResponse.FrequencyDistributionEntry\x12\x32\n\x08\x65ntities\x18\x03 \x03(\x0b\x32 .analyzer.AnalyzeResponse.Entity\x12\x36\n\tsentiment\x18\x04 \x01(\x0b\x32#.analyzer.AnalyzeResponse.Sentiment\x1a<\n\x1a\x46requencyDistributionEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a$\n\x06\x45ntity\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x1aR\n\tSentiment\x12\x10\n\x08positive\x18\x01 \x01(\x01\x12\x10\n\x08negative\x18\x02 \x01(\x01\x12\x0f\n\x07neutral\x18\x03 \x01(\x01\x12\x10\n\x08\x63ompound\x18\x04 \x01(\x01\x32Q\n\x0f\x41nalyzerService\x12>\n\x07\x41nalyze\x12\x18.analyzer.AnalyzeRequest\x1a\x19.analyzer.AnalyzeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyzer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYZERESPONSE_FREQUENCYDISTRIBUTIONENTRY']._loaded_options = None
  _globals['_ANALYZERESPONSE_FREQUENCYDISTRIBUTIONENTRY']._serialized_options = b'8\001'
  _globals['_ANALYZEREQUEST']._serialized_start=28
  _globals['_ANALYZEREQUEST']._serialized_end=85
  _globals['_ANALYZERESPONSE']._serialized_start=88
  _globals['_ANALYZERESPONSE']._serialized_end=507
  _globals['_ANALYZERESPONSE_FREQUENCYDISTRIBUTIONENTRY']._serialized_start=325
  _globals['_ANALYZERESPONSE_FREQUENCYDISTRIBUTIONENTRY']._serialized_end=385
  _globals['_ANALYZERESPONSE_ENTITY']._serialized_start=387
  _globals['_ANALYZERESPONSE_ENTITY']._serialized_end=423
  _globals['_ANALYZERESPONSE_SENTIMENT']._serialized_start=425
  _globals['_ANALYZERESPONSE_SENTIMENT']._serialized_end=507
  _globals['_ANALYZERSERVICE']._serialized_start=509
  _globals['_ANALYZERSERVICE']._serialized_end=590
# @@protoc_insertion_point(module_scope)
