# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analyzer.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'analyzer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61nalyzer.proto\x12\x08\x61nalyzer\"X\n\x0e\x41nalyzeRequest\x12\r\n\x05texts\x18\x01 \x03(\t\x12\x0f\n\x07headers\x18\x02 \x03(\t\x12\x13\n\x0b\x63ta_buttons\x18\x03 \x03(\t\x12\x11\n\tmeta_tags\x18\x04 \x03(\t\"\x8e\x01\n\x0f\x41nalyzeResponse\x12\x11\n\tsentiment\x18\x01 \x01(\t\x12\x1b\n\x13keyword_suggestions\x18\x02 \x03(\t\x12\x18\n\x10improved_headers\x18\x03 \x03(\t\x12\x14\n\x0cimproved_cta\x18\x04 \x03(\t\x12\x1b\n\x13seo_recommendations\x18\x05 \x03(\t2X\n\x0f\x41nalyzerService\x12\x45\n\x0e\x41nalyzeContent\x12\x18.analyzer.AnalyzeRequest\x1a\x19.analyzer.AnalyzeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyzer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYZEREQUEST']._serialized_start=28
  _globals['_ANALYZEREQUEST']._serialized_end=116
  _globals['_ANALYZERESPONSE']._serialized_start=119
  _globals['_ANALYZERESPONSE']._serialized_end=261
  _globals['_ANALYZERSERVICE']._serialized_start=263
  _globals['_ANALYZERSERVICE']._serialized_end=351
# @@protoc_insertion_point(module_scope)
